### ISSUE TITLE
Porting openai/gym's foundation classes to Gym.jl

### ISSUE THREAD

**Issue by kraftpunk97-zz** [FluxML/Gym.jl#5]
Hi. I just wanted to get an opinion on porting openai/gym's foundational classes (`Space`, `Env`, etc) to Gym.jl and then building additional environments atop these base classes. My reasoning is that for someone who is coming from using openai/gym, transitioning to Gym.jl will be effortless, because they'd already be familiar with underlying structure of the package.

**Comment by tejank10** [comment]
That's a good idea. A structured way to represent observation and action space is currently required.

**Comment by kraftpunk97-zz** [comment]
Cool. I'll start working on it right away.

**Comment by kraftpunk97-zz** [comment]
I wanted to know if for certain action spaces we should switch to 0-based indexing or stick with 1-based indexing. For example, should Discrete spaces begin with 0 or with 1?

**Comment by tejank10** [comment]
Beginning with 1 would make it more julia-like.

**Comment by kraftpunk97-zz** [comment]
Closing Issue!
